server:
    verbosity: 1

    interface: 0.0.0.0
    port: 5335
    access-control: 172.31.0.0/24 allow

    username: "unbound"
    chroot: ""

    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes

    root-hints: "/var/lib/unbound/root.hints"
    auto-trust-anchor-file: "/var/lib/unbound/root.key"

    harden-glue: yes
    harden-dnssec-stripped: yes
    harden-below-nxdomain: yes

    use-caps-for-id: no
    qname-minimisation: yes
    aggressive-nsec: yes

    edns-buffer-size: 1232
    prefetch: yes
    num-threads: 1

    hide-identity: yes
    hide-version: yes

    private-address: 10.0.0.0/8
    private-address: 172.16.0.0/12
    private-address: 192.168.0.0/16
    private-address: 169.254.0.0/16
    private-address: fd00::/8
    private-address: fe80::/10

